# Generated by Django 3.1.3 on 2021-07-06 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desks', '0002_organisation_orgemplyee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgEmplyee',
            new_name='OrgEmployee',
        ),
    ]
