# Generated by Django 3.1.3 on 2021-07-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0004_orgemployee_approved'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('slot', 'desk', 'user'), name='unique_booking'),
        ),
        migrations.AddConstraint(
            model_name='deskplan',
            constraint=models.UniqueConstraint(fields=('desk', 'plan'), name='unique_desk_plan'),
        ),
        migrations.AddConstraint(
            model_name='orgemployee',
            constraint=models.UniqueConstraint(fields=('employee', 'organisation'), name='unique_org_emp'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_slot'),
        ),
    ]
