# Generated by Django 3.1.3 on 2021-07-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0005_auto_20210707_0428'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgemployee',
            name='unique_org_emp',
        ),
    ]
