# Generated by Django 3.1.3 on 2021-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0006_auto_20210707_0437'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orgemployee',
            constraint=models.UniqueConstraint(fields=('employee', 'organisation'), name='unique_org_emp'),
        ),
    ]
