# Generated by Django 3.1.3 on 2021-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0009_auto_20210709_1827'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('floor',), name='unique_floor'),
        ),
    ]
