# Generated by Django 3.1.3 on 2021-07-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0010_auto_20210711_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='desks.plan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeskPlan',
        ),
    ]
