# Generated by Django 3.1.3 on 2021-07-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0011_auto_20210713_0429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
