# Generated by Django 3.1.3 on 2021-07-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210704_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xff71271890b285153e5d2601517ea941', max_length=128),
        ),
    ]
