# Generated by Django 3.1.3 on 2021-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210706_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xe7d9642b7bb3bc68b21ed33e706fe44e', max_length=128),
        ),
    ]
