# Generated by Django 3.1.3 on 2021-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210706_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x7700ee2ee86bce172ff28428efac3f8c', max_length=128),
        ),
    ]
