# Generated by Django 3.1.3 on 2021-07-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210706_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4ed56facf0357fcafde1a6cb849a334c', max_length=128),
        ),
    ]
