# Generated by Django 3.1.3 on 2021-07-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210707_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x70f997e0e832aae751758c03501b60cf', max_length=128),
        ),
    ]
