# Generated by Django 3.1.3 on 2021-07-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210707_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x913b88b635f6103e55f23a3420c95712', max_length=128),
        ),
    ]
