# Generated by Django 3.1.3 on 2021-07-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210707_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x9e34ffbad104e8d5d10858d171d3e586', max_length=128),
        ),
    ]
