# Generated by Django 3.1.3 on 2021-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210707_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xe35978095765732d9107df267e5c4f11', max_length=128),
        ),
    ]
