# Generated by Django 3.1.3 on 2021-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210709_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x2a0143d19d73cf19aac0dcf84f419876', max_length=128),
        ),
    ]
