# Generated by Django 3.1.3 on 2021-07-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210709_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x7abb668641a20a3e60ee0f69ea6c15b1', max_length=128),
        ),
    ]
