# Generated by Django 3.1.3 on 2021-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210711_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x29b6eefa86aad34e7c530e8657769edb', max_length=128),
        ),
    ]
