# Generated by Django 3.1.3 on 2021-07-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210713_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x8021570d6acc04e26d06f3bd8565c93d', max_length=128),
        ),
    ]
