# Generated by Django 3.1.3 on 2021-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210715_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x7e583fdb513a6f76514b96c586c2af59', max_length=128),
        ),
    ]
