# Generated by Django 3.1.3 on 2021-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210715_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xd54a3f5680827110bea88cc0ee0afa89', max_length=128),
        ),
    ]
