# Generated by Django 3.1.3 on 2021-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210715_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x2851367438eb4d8114f09cd1e92fb7cd', max_length=128),
        ),
    ]
