# Generated by Django 3.1.3 on 2021-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210715_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x26a3530e6af5437d6c67d4d54108b667', max_length=128),
        ),
    ]
