# Generated by Django 3.1.3 on 2021-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210715_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xf4b38fee7111a3d9821735682aeb4388', max_length=128),
        ),
    ]
