# Generated by Django 3.1.3 on 2021-07-15 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 5, 6, 22, 281995)),
            preserve_default=False,
        ),
    ]
