# Generated by Django 3.1.3 on 2021-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_slot'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='booking',
        #     name='unique_booking',
        # ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'desk', 'user'), name='unique_booking'),
        ),
    ]
