# Generated by Django 3.1.3 on 2021-08-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210715_0525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
    ]
